// Generated by https://quicktype.io

import {Sprites} from './pokemon-full';

export interface PokemonListResponse {
	count: number;
	next?: string;
	previous?: string;
	results: SmallPokemon[];
}

export interface SmallPokemon {
	name: string;
	url: string;
	id: number;
	img: string;
	gif: string;
	gifShiny: string;
}

export interface PokemonJSON {
	name: string;
	id: number;
	sprites: Sprites;
	gif: string;
	gifShiny: string;
}

export interface PokemonBasic {
	name: string;
	id: number;
}
